In [2]:
f = open('the-verdict.txt',encoding='utf-8')
rawtext  = f.read()
f.close()
print(len(rawtext))

with open('the-verdict.txt',encoding='utf-8') as f:
    rawtext  = f.read()
print(len(rawtext))



20479
20479


In [11]:
with open('file.ipynb','w+') as f:
    f.write("Hello , NEW file is created w!")
    f.seek(0)  
    raw = f.read()

print(len(raw))

30


In [ ]:
try:
    with open('txtfile.ipynb','x') as f:
        f.write('hello')
except FileExistsError:
    print("File does exist")


In [8]:
import re
rawdata = re.split(r'([,.]|\s)',rawtext)
print(rawdata)

# rawdata = [item for item in rawdata if item.strip()]
# print(rawdata)

rawdata = re.findall(r'\w+|[,.]',rawtext)
print(rawdata)

['I', ' ', 'HAD', ' ', 'always', ' ', 'thought', ' ', 'Jack', ' ', 'Gisburn', ' ', 'rather', ' ', 'a', ' ', 'cheap', ' ', 'genius--though', ' ', 'a', ' ', 'good', ' ', 'fellow', ' ', 'enough--so', ' ', 'it', ' ', 'was', ' ', 'no', ' ', 'great', ' ', 'surprise', ' ', 'to', ' ', 'me', ' ', 'to', ' ', 'hear', ' ', 'that', ',', '', ' ', 'in', ' ', 'the', ' ', 'height', ' ', 'of', ' ', 'his', ' ', 'glory', ',', '', ' ', 'he', ' ', 'had', ' ', 'dropped', ' ', 'his', ' ', 'painting', ',', '', ' ', 'married', ' ', 'a', ' ', 'rich', ' ', 'widow', ',', '', ' ', 'and', ' ', 'established', ' ', 'himself', ' ', 'in', ' ', 'a', ' ', 'villa', ' ', 'on', ' ', 'the', ' ', 'Riviera', '.', '', ' ', '(Though', ' ', 'I', ' ', 'rather', ' ', 'thought', ' ', 'it', ' ', 'would', ' ', 'have', ' ', 'been', ' ', 'Rome', ' ', 'or', ' ', 'Florence', '.', ')', '\n', '', '\n', '"The', ' ', 'height', ' ', 'of', ' ', 'his', ' ', 'glory"--that', ' ', 'was', ' ', 'what', ' ', 'the', ' ', 'women', ' ', 'called', ' ', 'it

In [9]:
allwords = sorted(set(rawdata))  # set for removing duplicates
print(allwords)

vocab = {integer:token for integer,token in enumerate(allwords)} # returns itterable and item
print(vocab)

[',', '.', 'A', 'Ah', 'Among', 'And', 'Are', 'Arrt', 'As', 'At', 'Be', 'Begin', 'Burlington', 'But', 'By', 'Carlo', 'Chicago', 'Claude', 'Come', 'Croft', 'Destroyed', 'Devonshire', 'Don', 'Dubarry_', 'Emperors', 'Florence', 'For', 'Gallery', 'Gideon', 'Gisburn', 'Gisburns', 'Grafton', 'Greek', 'Grindle', 'Grindles', 'HAD', 'Had', 'Hang', 'Has', 'He', 'Her', 'Hermia', 'His', 'How', 'I', 'If', 'In', 'It', 'Jack', 'Jove', 'Just', 'Lord', 'Made', 'Miss', 'Money', 'Monte', 'Moon', 'Mr', 'Mrs', 'My', 'Never', 'No', 'Now', 'Nutley', 'Of', 'Oh', 'On', 'Once', 'Only', 'Or', 'Perhaps', 'Poor', 'Professional', 'Renaissance', 'Rickham', 'Riviera', 'Rome', 'Russian', 'Sevres', 'She', 'Stroud', 'Strouds', 'Suddenly', 'That', 'The', 'Then', 'There', 'They', 'This', 'Those', 'Though', 'Thwing', 'Thwings', 'To', 'Usually', 'Venetian', 'Victor', 'Was', 'We', 'Well', 'What', 'When', 'Why', 'Yes', 'You', '_I', '_am_', '_famille', '_felt_', '_has_', '_have_', '_jardiniere_', '_mine_', '_not_', '_rose', '_r

In [12]:
for i , item in enumerate(vocab.items()):
    if(i<=50) :
        print(i,item)

0 (0, ',')
1 (1, '.')
2 (2, 'A')
3 (3, 'Ah')
4 (4, 'Among')
5 (5, 'And')
6 (6, 'Are')
7 (7, 'Arrt')
8 (8, 'As')
9 (9, 'At')
10 (10, 'Be')
11 (11, 'Begin')
12 (12, 'Burlington')
13 (13, 'But')
14 (14, 'By')
15 (15, 'Carlo')
16 (16, 'Chicago')
17 (17, 'Claude')
18 (18, 'Come')
19 (19, 'Croft')
20 (20, 'Destroyed')
21 (21, 'Devonshire')
22 (22, 'Don')
23 (23, 'Dubarry_')
24 (24, 'Emperors')
25 (25, 'Florence')
26 (26, 'For')
27 (27, 'Gallery')
28 (28, 'Gideon')
29 (29, 'Gisburn')
30 (30, 'Gisburns')
31 (31, 'Grafton')
32 (32, 'Greek')
33 (33, 'Grindle')
34 (34, 'Grindles')
35 (35, 'HAD')
36 (36, 'Had')
37 (37, 'Hang')
38 (38, 'Has')
39 (39, 'He')
40 (40, 'Her')
41 (41, 'Hermia')
42 (42, 'His')
43 (43, 'How')
44 (44, 'I')
45 (45, 'If')
46 (46, 'In')
47 (47, 'It')
48 (48, 'Jack')
49 (49, 'Jove')
50 (50, 'Just')


In [18]:
with open('the-verdict.txt',encoding='utf-8') as f:
    rawdata = f.read()

import tiktoken 
tokenizer = tiktoken.get_encoding('gpt2')
token_id = tokenizer.encode(rawdata)
print(len(token_id))
string_id = tokenizer.decode(token_id)

maxlength = 4
sample = token_id[:maxlength]
sample_target = token_id[1:maxlength+1]
print(sample)
print(sample_target)

5145
[40, 367, 2885, 1464]
[367, 2885, 1464, 1807]


In [9]:
for i in range (0 , maxlength):
    token_input = token_id[:i+1]
    token_target = token_id[i+1]
    print(token_input,"---->",token_target)

for i in range(0,maxlength):
    string_input = string_id[:i+1]
    string_target = string_id[i+1]
    print(string_input,"---->",string_target)


[40] ----> 367
[40, 367] ----> 2885
[40, 367, 2885] ----> 1464
[40, 367, 2885, 1464] ----> 1807
I ---->  
I  ----> H
I H ----> A
I HA ----> D


In [ ]:
import torch
enc_sample = token_id[:50]
print(len(enc_sample))

input_ids = []
target_ids = []
for i in range(0,len(enc_sample)-maxlength,maxlength):
    input_chunk = enc_sample[i:i+maxlength]
    target_chunk = enc_sample[i+1:i+maxlength+1]
    input_ids.append(torch.tensor(input_chunk))
    target_ids.append(torch.tensor(target_chunk))

print(len(input_ids))
# print(target_ids)

50
12


In [20]:
from torch.utils.data import Dataset , DataLoader

class SimpleDataset(Dataset):
    def __init__(self, maxlength ,stride,text,tokenizer):
        self.input_id = []
        self.target_id = []

        token_id = tokenizer.encode(text,allowed_special={'<|endoftext|>'})

        for i in range(0,len(token_id)-maxlength,stride):
            input_chunk = token_id[i:i+maxlength]
            target_chunk = token_id[i+1:i+maxlength+1]
            self.input_id.append(torch.tensor(input_chunk))
            self.target_id.append(torch.tensor(target_chunk))

    def __len__(self):
        return len(self.input_id)
    
    def __getitem__(self, index):
        return self.input_id[index],self.target_id[index]
    

    
def create_dataload(text,batch_size = 4,stride = 128,shuffle = True, maxlength = 256,drop_last =True ,numberofworker = 0):

    tokenizer = tiktoken.get_encoding('gpt2')

    dataset = SimpleDataset(maxlength,stride,text,tokenizer)

    dataloader = DataLoader(dataset,
                            batch_size=batch_size,
                            shuffle=shuffle,
                            drop_last=drop_last,
                            num_workers=numberofworker)
    
    return dataloader


In [22]:
dataloader = create_dataload(rawdata,batch_size=8,stride=4,maxlength=4,shuffle=False)
data_iter = iter(dataloader)
inputs,targets = next(data_iter)
print("Inputs:\n", inputs)
print("\nTargets:\n", targets)

Inputs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])

Targets:
 tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922],
        [ 5891,  1576,   438,   568],
        [  340,   373,   645,  1049],
        [ 5975,   284,   502,   284],
        [ 3285,   326,    11,   287]])


In [25]:
torch.manual_seed(123)
embeddiglayer = torch.nn.Embedding(4,4)
print(embeddiglayer.weight)
print(embeddiglayer(torch.tensor([1])))

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.3035, -0.5880],
        [ 0.3486,  0.6603, -0.2196, -0.3792],
        [ 0.7671, -1.1925,  0.6984, -1.4097],
        [ 0.1794,  1.8951,  0.4954,  0.2692]], requires_grad=True)
tensor([[ 0.3486,  0.6603, -0.2196, -0.3792]], grad_fn=<EmbeddingBackward0>)


In [33]:
input_ids=torch.tensor([2,3,1])
print(embeddiglayer(input_ids))

tensor([[ 0.7671, -1.1925,  0.6984, -1.4097],
        [ 0.1794,  1.8951,  0.4954,  0.2692],
        [ 0.3486,  0.6603, -0.2196, -0.3792]], grad_fn=<EmbeddingBackward0>)


In [ ]:
with open('the-verdict.txt',encoding='utf-8') as f:
    rawdata = f.read()

import torch
import tiktoken
from torch.utils.data import Dataset,DataLoader

class Simpledataset(Dataset):
    def __init__(self,text,tokenizer,maxlength,stride):
        self.input_id = []
        self.target_id = []

        token_ids = tokenizer.encode(text,allowed_special={'<|endoftext|>'})
        
        for i in range(0,len(token_ids)-maxlength,stride):
            input_chunks = token_ids[i:i+maxlength]
            target_chunks = token_ids[i+1:i+maxlength+1]
            self.input_id.append(torch.tensor(input_chunks))
            self.target_id.append(torch.tensor(target_chunks))

    def __len__(self):
        return len(self.input_id)
    
    def __getitem__(self, index):
        return self.input_id[index],self.target_id[index]
    

def create_dataloader(text,batch_size = 4,stride = 4,maxlength = 4,shuffle=False,drop_last=True,number_of_workers=0):

        tokenizer = tiktoken.get_encoding('gpt2')

        dataset = Simpledataset(text,tokenizer=tokenizer,maxlength=maxlength,stride=stride)

        dataloader = DataLoader(
            dataset=dataset,
            batch_size=batch_size,
            shuffle=shuffle,
            drop_last=drop_last,
            num_workers=number_of_workers
        )

        return dataloader
    
dataloader = create_dataloader(text=rawdata)
data_iter = iter(dataloader)
inputs,targets = next(data_iter)
print(inputs)
print(targets)


tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257]])
tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922]])


In [22]:
token_embedding_layer = torch.nn.Embedding(50257,256)
position_embedding_layer = torch.nn.Embedding(4,256)

token_embedding = token_embedding_layer(inputs)
position_embedding = position_embedding_layer(torch.arange(4))
inputs = token_embedding+position_embedding

In [25]:
import torch

inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

In [26]:
attention_score = torch.empty(inputs.shape)

# for i,x_i in enumerate(inputs):
#     for j,x_j in enumerate(inputs):
#         attention_score[i][j] = torch.dot(x_i,x_j)

# print(attention_score)

attention_score = inputs @ inputs.T
print(attention_score)
attention_weight = torch.softmax(attention_score,dim = -1)
print(attention_weight)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])
tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])
